on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string


jobs:
  doit:
    - uses: phargogh/test-gha-workflow-chaining-child/.github/workflows/child-workflow.yml@main

#  doit:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: phargogh/test-gha-workflow-chaining-child/.github/workflows/child-workflow.yml@main
#        with:
#          some_parameter: "this is a test"
#

